language: node_js

node_js:
  - lts/*

services: mongodb

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: Deploy Backend
      script: skip
      before_deploy:
        - cd backend
      deploy:
        provider: heroku
        api_key:
          secure: NrwfeICKXUeaNHoFBZplagGXvR9PeHWe5wIDtpfEyEtOf3EGPNoU0fPDR5Ad8q1yxEFP1j9Gvm1XVn7VFEKddcbCMUktm96UbbhtvaAlEykg4+nb/4dnDU9qDJZmvEiKuSWixfcXv5PSiq3wLhEx1L7wA8S3U8rvjOnfTig5avEt2WjV3wxws/mHseX5SYhjtE/KEOfa0a0aGKuU/uQKbpOieuvFCWmIf5EXcliklXiUSi6oIrwltfVvNsPrwB3nXGapFHGiDUgHwe44rqcBchQPCOHZr8KMnu711SbzI6vQgRO1DR46ZndfKvhbXyeW0bPKn3H2CHv2zqIfQJLEA2+PiSJrXBAihDi2QEq84TlijEERJR1a6JzaCmIS7gk2FyMiZkDd/pqzAYd3LmhpxHGxf8QFVbCMgm+xc/BQToe59BQ1dJ2rnPr+U5Ic4+JlqIr6LHE4c9d1qkLixkEcsxfajYcV0gqpUx6sYnAaE5vzGvTaTKFfSGGvyOXNQceJr0oKQ+H7+Qhl3JU4L9hg7s5dHx+FlHjiJlziZD8DAGMKczpdgQUYhenzxkgbDEA8VEvM1471iS29UsosNUv5PZi84YZURfJHv4plkep7/TC746SREDEi4oytAx2d/zEEPbJ+09FTHoB6kWP7oFZ3Ze9JohePnyActilVDK0nUxg=
        app: opt-vis-backend
        on:
          repo: GoelBiju/Visualising-Optimisation-Data
          branch: main

    # - stage: Lint
    #   name: Frontend
    #   script: yarn lint:frontend

    # - stage: Unit Tests
    #   name: Frontend
    #   script: yarn test:frontend

    - stage: Deploy Frontend
      script: skip
      before_deploy:
        - yarn workspace frontend build
        - cd packages/frontend
      deploy:
        provider: heroku
        api_key:
          secure: NrwfeICKXUeaNHoFBZplagGXvR9PeHWe5wIDtpfEyEtOf3EGPNoU0fPDR5Ad8q1yxEFP1j9Gvm1XVn7VFEKddcbCMUktm96UbbhtvaAlEykg4+nb/4dnDU9qDJZmvEiKuSWixfcXv5PSiq3wLhEx1L7wA8S3U8rvjOnfTig5avEt2WjV3wxws/mHseX5SYhjtE/KEOfa0a0aGKuU/uQKbpOieuvFCWmIf5EXcliklXiUSi6oIrwltfVvNsPrwB3nXGapFHGiDUgHwe44rqcBchQPCOHZr8KMnu711SbzI6vQgRO1DR46ZndfKvhbXyeW0bPKn3H2CHv2zqIfQJLEA2+PiSJrXBAihDi2QEq84TlijEERJR1a6JzaCmIS7gk2FyMiZkDd/pqzAYd3LmhpxHGxf8QFVbCMgm+xc/BQToe59BQ1dJ2rnPr+U5Ic4+JlqIr6LHE4c9d1qkLixkEcsxfajYcV0gqpUx6sYnAaE5vzGvTaTKFfSGGvyOXNQceJr0oKQ+H7+Qhl3JU4L9hg7s5dHx+FlHjiJlziZD8DAGMKczpdgQUYhenzxkgbDEA8VEvM1471iS29UsosNUv5PZi84YZURfJHv4plkep7/TC746SREDEi4oytAx2d/zEEPbJ+09FTHoB6kWP7oFZ3Ze9JohePnyActilVDK0nUxg=
        app: opt-vis-frontend
        on:
          repo: GoelBiju/Visualising-Optimisation-Data
          branch: main

    - stage: Deploy Frontend Plugin
      script: skip
      before_deploy:
        - yarn workspace frontend-plugin build
        - cd packages/frontend-plugin
      deploy:
        provider: heroku
        api_key:
          secure: NrwfeICKXUeaNHoFBZplagGXvR9PeHWe5wIDtpfEyEtOf3EGPNoU0fPDR5Ad8q1yxEFP1j9Gvm1XVn7VFEKddcbCMUktm96UbbhtvaAlEykg4+nb/4dnDU9qDJZmvEiKuSWixfcXv5PSiq3wLhEx1L7wA8S3U8rvjOnfTig5avEt2WjV3wxws/mHseX5SYhjtE/KEOfa0a0aGKuU/uQKbpOieuvFCWmIf5EXcliklXiUSi6oIrwltfVvNsPrwB3nXGapFHGiDUgHwe44rqcBchQPCOHZr8KMnu711SbzI6vQgRO1DR46ZndfKvhbXyeW0bPKn3H2CHv2zqIfQJLEA2+PiSJrXBAihDi2QEq84TlijEERJR1a6JzaCmIS7gk2FyMiZkDd/pqzAYd3LmhpxHGxf8QFVbCMgm+xc/BQToe59BQ1dJ2rnPr+U5Ic4+JlqIr6LHE4c9d1qkLixkEcsxfajYcV0gqpUx6sYnAaE5vzGvTaTKFfSGGvyOXNQceJr0oKQ+H7+Qhl3JU4L9hg7s5dHx+FlHjiJlziZD8DAGMKczpdgQUYhenzxkgbDEA8VEvM1471iS29UsosNUv5PZi84YZURfJHv4plkep7/TC746SREDEi4oytAx2d/zEEPbJ+09FTHoB6kWP7oFZ3Ze9JohePnyActilVDK0nUxg=
        app: opt-vis-frontend-plugin
        on:
          repo: GoelBiju/Visualising-Optimisation-Data
          branch: main
