language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
install:
  - yarn install --frozen-lockfile
jobs:
  include:
    - stage: "Lint"
      name: "Frontend"
      script: yarn lint:frontend

    - stage: "Unit tests"
      name: "Frontend"
      script: yarn test:frontend
